const t = require('tap')
const map = require('../map.js')
t.equal(map('test/index.js'), 'index.js')
t.same(map('test/unpack.js'), ['lib/unpack.js', 'lib/mkdir.js', 'lib/normalize-unicode.js'])
t.same(map('test/ghsa-r6q2-hw4h-h46w.js'), ['lib/normalize-unicode.js', 'lib/extract.js', 'lib/header.js'])
t.same(map('test/load-all.js'), [])
t.equal(map(__filename), 'map.js')
t.equal(map('test/asdf'), 'lib/asdf')
